displayName: 升级管理
get:
  description: 升级信息列表
  securedBy: [ auth-box ]
  is: [ secured, rate-limited, pageable, searchable: {description: "with valid searchable fields: type, state", example: "[\"type\", \"boxos\", \"equal\"]"} ]
  responses:
    200:
      body:
        application/json:
          type: upgrades
          example: !include example/upgrades.json

post:
  description: |
    创建升级信息。

    此时升级信息的状态必须是“待测试”。
  securedBy: [ auth-box ]
  is: [ secured, rate-limited ]
  body:
    application/json:
      type: upgrade
      example: !include example/upgrade.json
  responses:
    200:
      body:
        application/json:
          type: upgrade
          example: !include example/upgrade.json

/{id}:
  uriParameters:
    id:
      type: int
      description: 升级信息ID
      required: true
  get:
    description: 升级信息详情
    securedBy: [ auth-box ]
    is: [ secured, rate-limited ]
    responses:
      200:
        body:
          application/json:
            type: upgrade
            example: !include example/upgrade.json
  delete:
    description: 删除升级信息
    securedBy: [ auth-box ]
    is: [ secured, rate-limited, deleteable ]
  put:
    description: |
      修改升级信息

      在此可以将升级信息的状态改为 "测试失败", "待发布", "已发布"。
      状态为"已发布"的升级信息保存在缓存中的 "upgrade.release.${type}" Hash Table
      其它状态升级信息保存在缓存中的 "upgrade.prerelease.${type}" Hash Table
      两个 Hash Table 中的 key 是 "${system-board}-${lock-board}"，value 是升级索引文件的 URL
    securedBy: [ auth-box ]
    is: [ secured, rate-limited ]
    body:
      application/json:
        type: upgrade
        example: !include example/upgrade.json
    responses:
      200:
        body:
          application/json:
            type: upgrade
            example: !include example/upgrade.json

/stages:
  /latest:
    get:
      description: 获取最新 stage 内的所有升级信息
      securedBy: [ auth-box ]
      is: [ secured, rate-limited, pageable ]
      responses:
        200:
          body:
            application/json:
              type: upgrades
              example: !include example/upgrades.json
